# Generated by Django 5.0.2 on 2024-02-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=200)),
                ('pet_age', models.IntegerField()),
                ('pet_gender', models.CharField(max_length=200)),
                ('pet_color', models.CharField(max_length=200)),
                ('pet_type', models.CharField(max_length=200)),
                ('pet_description', models.TextField()),
                ('pet_image', models.ImageField(upload_to='images/')),
                ('pet_price', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='Toys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toy_name', models.CharField(max_length=200)),
                ('toy_type', models.CharField(max_length=200)),
                ('toy_description', models.CharField(max_length=200)),
            ],
        ),
    ]
