# Generated by Django 5.0.1 on 2024-02-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_bio', models.TextField()),
                ('profile_image', models.ImageField(upload_to='profile/')),
                ('dat_created', models.DateTimeField(auto_now_add=True)),
                ('data_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
