# Generated by Django 5.0.1 on 2024-03-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_clientprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
